/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import clases.Cliente;
import clases.Producto;
import clases.Venta;
import clases.VentaDetalle;
import javax.swing.JOptionPane;

/**
 *
 * @author alfreding0
 */
public class FormDetalle extends javax.swing.JFrame {

    private final Cliente cliente = new Cliente();
    private final Producto producto = new Producto();
    
    public FormDetalle() {
        initComponents();
        
        this.setLocationRelativeTo(null); //la ventana quede centrada
        
        producto.listarProductos(jComboBoxProducto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtBuscarCICliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtCIPersonal = new javax.swing.JTextField();
        jLabelStockProducto = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txtNombreCliente = new javax.swing.JTextField();
        jTextFieldPrecioProducto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jComboBoxProducto = new javax.swing.JComboBox<>();
        jSpinnerCantidad = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jSpinnerIDVenta = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("VENTA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 153, 47));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID_VENTA", "PRODUCTO", "PRECIO_UNID", "CANTIDAD"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 336, 601, 110));

        jTextField1.setEditable(false);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 450, 150, 26));

        jLabel2.setText("TOTAL (Bs):");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, -1, 20));
        getContentPane().add(txtBuscarCICliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 117, 130, 24));

        jLabel5.setText("Cantidad:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 110, 20));

        jButton1.setText("-O");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 57, -1));

        jButton2.setText("-O");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 57, 30));

        txtCIPersonal.setText("9823548");
        getContentPane().add(txtCIPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 218, 129, 30));

        jLabelStockProducto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelStockProducto.setForeground(new java.awt.Color(255, 102, 51));
        jLabelStockProducto.setText("10 Unid.");
        getContentPane().add(jLabelStockProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 81, 30));

        jButton3.setText("Guardar Venta");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        txtNombreCliente.setEditable(false);
        getContentPane().add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 153, 170, 26));
        getContentPane().add(jTextFieldPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 150, 30));

        jLabel7.setText("NºVENTA:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 87, 30));

        jLabel9.setText("Precio Unidad (Bs):");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 150, 20));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/guardar-20.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 40, 30));

        jComboBoxProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProductoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 210, 30));

        jSpinnerCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        getContentPane().add(jSpinnerCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 110, 30));

        jLabel8.setText("PERSONAL");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 81, 30));

        jSpinnerIDVenta.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        getContentPane().add(jSpinnerIDVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 130, 30));

        jLabel10.setText("CLIENTE");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 117, 87, 24));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.buscarClientePorCI();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProductoActionPerformed
        this.obtenerDatosDelProducto();
    }//GEN-LAST:event_jComboBoxProductoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.guardarVenta();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.agregarProductoAlDetalle();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDetalle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<Producto> jComboBoxProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelStockProducto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerCantidad;
    private javax.swing.JSpinner jSpinnerIDVenta;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldPrecioProducto;
    private javax.swing.JTextField txtBuscarCICliente;
    private javax.swing.JTextField txtCIPersonal;
    private javax.swing.JTextField txtNombreCliente;
    // End of variables declaration//GEN-END:variables

    private void buscarClientePorCI() {
        txtNombreCliente.setText("");
        
        String ci = txtBuscarCICliente.getText();
        cliente.setCi(ci);
        
        cliente.buscarClientePorCI(txtBuscarCICliente, txtNombreCliente);
    }

    private void obtenerDatosDelProducto() {
        //limpiar el texto cuando sea la primera opcioni
        jTextFieldPrecioProducto.setText("");
        jLabelStockProducto.setText("");
        
        int item = jComboBoxProducto.getSelectedIndex();
        
        if ( item != 0){
            String precio = jComboBoxProducto.getItemAt(jComboBoxProducto.getSelectedIndex()).getPrecio();
            String stock = jComboBoxProducto.getItemAt(jComboBoxProducto.getSelectedIndex()).getStock();
            
            jTextFieldPrecioProducto.setText(precio);
            jLabelStockProducto.setText(stock + " Unids.");
        }
    }

    private void guardarVenta() {
        Venta venta = new Venta();
        
        venta.setCi_cliente(txtBuscarCICliente.getText());
        venta.setCi_personal(txtCIPersonal.getText());
        
        venta.guardarVenta();
    }

    private void agregarProductoAlDetalle() {        
        VentaDetalle detalle = new VentaDetalle(
                jSpinnerIDVenta.getModel().getValue().toString(), 
                jComboBoxProducto.getItemAt(jComboBoxProducto.getSelectedIndex()).getId(), 
                jTextFieldPrecioProducto.getText(), 
                jSpinnerCantidad.getModel().getValue().toString()
        );
        
        detalle.guardarVentaDetalle();
        
        detalle.mostrarVentaDetalle(jTable1);
    }
}
