/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import clases.Cliente;
import clases.Producto;
import clases.VentaDetalle;

/**
 *
 * @author alfreding0
 */
public class FormDetalleVenta extends javax.swing.JFrame {

    private final Cliente cliente = new Cliente();
    private final Producto producto = new Producto();
    private final VentaDetalle detalle = new VentaDetalle();
    
    public FormDetalleVenta(String id_venta, String total, String fecha, String hora, String ci_cliente, String ci_personal) {
        initComponents();
        
        this.setLocationRelativeTo(null); //la ventana quede centrada
        
        producto.listarProductos(jComboBoxProducto);
        
        this.jTextFieldIDVENTA.setText(id_venta);
        this.jTextFieldTOTAL.setText(total);
        this.jTextFieldFECHA.setText(fecha);
        this.jTextFieldHORA.setText(hora);
        this.jTextFieldCLIENTE.setText(ci_cliente);
        this.jTextFieldPERSONA.setText(ci_personal);
        
        this.mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCLIENTE = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabelStockProducto = new javax.swing.JLabel();
        jTextFieldPrecioProducto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jComboBoxProducto = new javax.swing.JComboBox<>();
        jSpinnerCantidad = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldIDVENTA = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldTOTAL = new javax.swing.JTextField();
        jTextFieldFECHA = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldHORA = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldPERSONA = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("VENTA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 153, 47));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 601, 110));

        jTextField1.setEditable(false);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 150, 26));

        jLabel2.setText("TOTAL (Bs):");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, -1, 20));

        jTextFieldCLIENTE.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jTextFieldCLIENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 94, 110, 30));

        jLabel5.setText("Cantidad:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 110, 20));

        jLabelStockProducto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelStockProducto.setForeground(new java.awt.Color(255, 102, 51));
        jLabelStockProducto.setText("10 Unid.");
        getContentPane().add(jLabelStockProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 81, 30));
        getContentPane().add(jTextFieldPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 150, 30));

        jLabel7.setText("NºVENTA:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 87, 30));

        jLabel9.setText("Precio Unidad (Bs):");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 150, 20));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/guardar-20.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 40, 30));

        jComboBoxProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProductoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 210, 30));

        jSpinnerCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        getContentPane().add(jSpinnerCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 110, 30));

        jLabel10.setText("CLIENTE");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 70, 24));

        jTextFieldIDVENTA.setEditable(false);
        jTextFieldIDVENTA.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jTextFieldIDVENTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 80, 30));

        jLabel11.setText("TOTAL Bs();");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 70, 30));

        jTextFieldTOTAL.setEditable(false);
        jTextFieldTOTAL.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jTextFieldTOTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 90, 30));

        jTextFieldFECHA.setEditable(false);
        jTextFieldFECHA.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jTextFieldFECHA, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 110, 30));

        jLabel12.setText("FECHA");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 100, 30));

        jLabel13.setText("HORA");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 100, 30));

        jTextFieldHORA.setEditable(false);
        jTextFieldHORA.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jTextFieldHORA, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 110, 30));

        jLabel14.setText("PERSONAL");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 70, 24));

        jTextFieldPERSONA.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jTextFieldPERSONA, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 94, 100, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProductoActionPerformed
        this.obtenerDatosDelProducto();
    }//GEN-LAST:event_jComboBoxProductoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.agregarProductoAlDetalle();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        int fila = jTable1.getSelectedRow();
        
        jComboBoxProducto.setSelectedIndex(Integer.parseInt(jTable1.getValueAt(fila, 1).toString()));
    }//GEN-LAST:event_jTable1MouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<Producto> jComboBoxProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelStockProducto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerCantidad;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldCLIENTE;
    private javax.swing.JTextField jTextFieldFECHA;
    private javax.swing.JTextField jTextFieldHORA;
    private javax.swing.JTextField jTextFieldIDVENTA;
    private javax.swing.JTextField jTextFieldPERSONA;
    private javax.swing.JTextField jTextFieldPrecioProducto;
    private javax.swing.JTextField jTextFieldTOTAL;
    // End of variables declaration//GEN-END:variables


    private void obtenerDatosDelProducto() {
        //limpiar el texto cuando sea la primera opcioni
        jTextFieldPrecioProducto.setText("");
        jLabelStockProducto.setText("");
        
        int item = jComboBoxProducto.getSelectedIndex();
        
        if ( item != 0){
            String precio = jComboBoxProducto.getItemAt(jComboBoxProducto.getSelectedIndex()).getPrecio();
            String stock = jComboBoxProducto.getItemAt(jComboBoxProducto.getSelectedIndex()).getStock();
            
            jTextFieldPrecioProducto.setText(precio);
            jLabelStockProducto.setText(stock + " Unids.");
        }
    }
    
    private void agregarProductoAlDetalle() {        
        VentaDetalle detalle = new VentaDetalle(
                jTextFieldIDVENTA.getText(), 
                jComboBoxProducto.getItemAt(jComboBoxProducto.getSelectedIndex()).getId(), 
                jTextFieldPrecioProducto.getText(), 
                jSpinnerCantidad.getModel().getValue().toString()
        );
        
        detalle.guardarVentaDetalle();
        this.mostrar();
    }
    
    private void mostrar(){
        detalle.setId_venta(jTextFieldIDVENTA.getText());
        detalle.mostrarVentaDetalle(jTable1);
    }
}
